[model]
name = "meta-llama/Llama-3.2-1B-Instruct"

[training]
data_path = "data/train.json"
sample_size = 100
batch_size = 8
seed = 0

[testing]
data_path = "data/test.json"
batch_size = 8
claim_key = "claims"
output_path = "output/test_decision.txt"
